In [26]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier

In [27]:
df=pd.read_excel("iris-train.xlsx")

In [28]:
df.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [29]:
x=df.iloc[ : , :-1]

In [30]:
x   ##features

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [31]:
y= df.iloc[ : ,-1]

In [32]:
y  ## labels

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [33]:
model=RandomForestClassifier()

In [34]:
model=model.fit(x.values,y.values)

In [35]:
prediction=model.predict([[5.4,	3,	4.5	,1.5]])

In [36]:
prediction

array(['Iris-versicolor'], dtype=object)

In [37]:







df_test=pd.read_excel("iris-test.xlsx");

In [38]:
x_test=df_test.iloc[ : , :-1]

In [39]:
prediction=model.predict(x_test.values)

In [40]:
prediction

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [41]:
y_test=df_test.iloc[ : , -1]

In [42]:
actual=y_test.values

In [46]:
count=0

for i in range(0,len(actual)):
    
    if prediction[i]==actual[i]:
        count=count+1
        
print((count*100)/len(actual))

97.05882352941177