In [59]:
import pandas as pd

In [60]:
data=[ ["gaurav",100] , ["rohit",99] , ["aman" , 88]]  #dataframe using pyhton list

In [61]:
data

[['gaurav', 100], ['rohit', 99], ['aman', 88]]

In [62]:
pd.DataFrame(data, columns=["Name", "Marks"])

     Name  Marks
0  gaurav    100
1   rohit     99
2    aman     88

In [63]:
data2= {"a":[1,2,3]  , "b":[4,5,6]}   #dataframe using dictionary of list

In [64]:
data2

{'a': [1, 2, 3], 'b': [4, 5, 6]}

In [65]:
pd.DataFrame(data2)

   a  b
0  1  4
1  2  5
2  3  6

In [66]:
import numpy as np

In [67]:
arr= np.array([[1,2] ,[3,4]])      #dataframe using numpy

In [68]:
df=pd.DataFrame(arr, columns=["A","B"])

In [69]:
df

   A  B
0  1  2
1  3  4

In [70]:
df=pd.read_excel("data.xlsx")

In [71]:
df

     Name School   Marks
0  gaurav      aa    100
1    aman      bb     12
2   rohit      cc     22
3     ram      dd     34
4   sneha      ee     45
5    rock      ff     89
6    ramu      hh     44
7   shamu      ii     66

In [72]:
df=pd.read_csv("data.csv")

In [73]:
df

     Name School   Marks
0  gaurav      aa    100
1    aman      bb     12
2   rohit      cc     22
3     ram      dd     34
4   sneha      ee     45
5    rock      ff     89
6    ramu      hh     44
7   shamu      ii     66

In [74]:
df= pd.read_json("data.json")

In [75]:
df

     Name    Lang
0  gaurav  python
1   amana      js

In [76]:
df= pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [58]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [77]:
#EDA

In [78]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [80]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [88]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [91]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [92]:
df.size

1708