In [21]:
import pandas as pd

In [22]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [23]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [24]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [25]:
pd.merge(employees,departments, on ="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [26]:
pd.merge(employees,departments , on="DeptID" , how="left") #left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [27]:
pd.merge(employees,departments , on="DeptID" ,how="right") #right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [28]:
pd.merge(employees, departments ,on="DeptID" , how="outer") ##outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [29]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [30]:
df1

    Name
0  Alice
1    Bob

In [31]:
df2

      Name
0  Charlie
1    David

In [32]:
pd.concat([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [33]:
pd.concat([df1,df2] , axis=1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [34]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80

In [35]:
pd.concat([df1,df2],axis=0)

    ID  Score
0  1.0    NaN
1  2.0    NaN
0  NaN   90.0
1  NaN   80.0